// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project_2

#ifndef _SQUARELINE_PROJECT_2_UI_H
#define _SQUARELINE_PROJECT_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(OnButtonClick_t on_button3_click, OnButtonClick_t on_button4_click, OnSliderChange_t on_slider_change);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
