// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project_2

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_humidity = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_temperature1 = NULL;
lv_obj_t * ui_humidity1 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(OnButtonClick_t on_button3_click, OnButtonClick_t on_button4_click, OnSliderChange_t on_slider_change)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Button");

    ui_Switch1 = lv_switch_create(ui_TabPage2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -59);
    lv_obj_set_y(ui_Switch1, -39);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Switch1, on_button3_click, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Switch2 = lv_switch_create(ui_TabPage2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -58);
    lv_obj_set_y(ui_Switch2, 10);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Switch2, on_button4_click, LV_EVENT_VALUE_CHANGED, NULL);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Sensor");

    ui_humidity = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, 15);
    lv_obj_set_y(ui_humidity, 29);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity, "text");
    lv_obj_set_style_text_font(ui_humidity, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -75);
    lv_obj_set_y(ui_temperature, -48);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "Temp");
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature1 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_temperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature1, 15);
    lv_obj_set_y(ui_temperature1, -49);
    lv_obj_set_align(ui_temperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature1, "text");
    lv_obj_set_style_text_font(ui_temperature1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity1 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_humidity1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity1, -74);
    lv_obj_set_y(ui_humidity1, 28);
    lv_obj_set_align(ui_humidity1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity1, "Hum");
    lv_obj_set_style_text_font(ui_humidity1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Led Strip");

    ui_Slider1 = lv_slider_create(ui_TabPage3);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, 10);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_slider_set_range(ui_Slider1, 0, 255);

    lv_obj_add_event_cb(ui_Slider1, on_slider_change, LV_EVENT_VALUE_CHANGED, NULL);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Slider2 = lv_slider_create(ui_TabPage3);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 59);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_slider_set_range(ui_Slider2, 0, 255);

    lv_obj_add_event_cb(ui_Slider2, on_slider_change, LV_EVENT_VALUE_CHANGED, NULL);
    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Slider3 = lv_slider_create(ui_TabPage3);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 150);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, 0);
    lv_obj_set_y(ui_Slider3, -44);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_slider_set_range(ui_Slider3, 0, 255);

    lv_obj_add_event_cb(ui_Slider3, on_slider_change, LV_EVENT_VALUE_CHANGED, NULL);
    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider3,
                                                                                              lv_obj_get_style_pad_right(ui_Slider3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label5 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, -71);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Red");

    ui_Label6 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 2);
    lv_obj_set_y(ui_Label6, -19);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Green");

    ui_Label7 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 3);
    lv_obj_set_y(ui_Label7, 35);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Blue");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage2 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_TabPage1 = NULL;
    ui_humidity = NULL;
    ui_temperature = NULL;
    ui_temperature1 = NULL;
    ui_humidity1 = NULL;
    ui_TabPage3 = NULL;
    ui_Slider1 = NULL;
    ui_Slider2 = NULL;
    ui_Slider3 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;

}
