// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project_2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

typedef void OnButtonClick_t(lv_event_t * e);
typedef void OnSliderChange_t(lv_event_t * e);

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(OnButtonClick_t on_button3_click, OnButtonClick_t on_button4_click, OnSliderChange_t on_slider_change);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_temperature1;
extern lv_obj_t * ui_humidity1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

